// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHrH99trKSrufs-HoKFXyZ2MHre1k97SU',
    appId: '1:469371191227:web:af37309023b984b3264e9e',
    messagingSenderId: '469371191227',
    projectId: 'sekolahku-9e4b7',
    authDomain: 'sekolahku-9e4b7.firebaseapp.com',
    storageBucket: 'sekolahku-9e4b7.appspot.com',
    measurementId: 'G-SPFXJ48KH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDfw152l5JPBNaEhlRsy1VV77UJzWTXjs',
    appId: '1:469371191227:android:1aa90f88918ec202264e9e',
    messagingSenderId: '469371191227',
    projectId: 'sekolahku-9e4b7',
    storageBucket: 'sekolahku-9e4b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7RHroGR2v2DhkKihw5sFqJV8QvDAX2A',
    appId: '1:469371191227:ios:80c1560f5097c631264e9e',
    messagingSenderId: '469371191227',
    projectId: 'sekolahku-9e4b7',
    storageBucket: 'sekolahku-9e4b7.appspot.com',
    androidClientId: '469371191227-4dt1ni7pl23dr4a9mdj6ac1ekl584u84.apps.googleusercontent.com',
    iosClientId: '469371191227-bvubmo1t8i7ktnn8a9b94q2knhipe0ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.sekolahku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ7RHroGR2v2DhkKihw5sFqJV8QvDAX2A',
    appId: '1:469371191227:ios:80c1560f5097c631264e9e',
    messagingSenderId: '469371191227',
    projectId: 'sekolahku-9e4b7',
    storageBucket: 'sekolahku-9e4b7.appspot.com',
    androidClientId: '469371191227-4dt1ni7pl23dr4a9mdj6ac1ekl584u84.apps.googleusercontent.com',
    iosClientId: '469371191227-bvubmo1t8i7ktnn8a9b94q2knhipe0ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.sekolahku',
  );
}
